# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1a36vhE1wWpGed_Wcu6iGkHCdoMSTAHhD
"""

1+1

a=10;



b=40

type(b)



y=9.7

type(y)

print("hello SRMCEM")

s="SRMCEM"

s[0:3:-5]

True/False

False/True

S="TRUE"

print(S)

t="Batch name is Computer Science & Engineering"

t[0:16:7]

t[0:16:90]

t[-3:-44:-5]

l=["deepali.",9.1,"certificateproducer",8.96,4+3j]

l[4].real

l[4].imag

type(l)

type(l[4])

d="Ramswar  oop"

d.count('o')

d.count('')

d.find('s')

d.lower()

d.upper()

len(d)

l[::-1]

d[::-1]

l.append(67)

l.pop()

l.pop()

l.insert(0,56)

print(l)

l.insert(4,570)

print(l)

r=(24,"shyam","it",23,"supercalifrajilisticexpilodicious",54,76,840)

r[0:7:1]

r.count(24)

len(r[4])

dict={"name":'age',"Ramesh":89,"Mushkaan":23}

dict["name"]

dict['Ramesh']

len(dict)

l=["ram","rahul",43,65,76]

len(l)

l.remove(43)

print(l)

marks=34
if marks>89:
  print("pass")
elif marks>70:
  print("distinction")
else:
  print("fail")

x=int(input())
if x>90:
  print("a+")
elif 80<x<90:
  print("a")
elif 70<x<79:
  print("b+")
elif 60<x<69:
  print("b")
else :
  print("f")

menu={
    "Cold Tea":90,
    "Black coffe":50,
    "lemonade":60,
    "Hot coffe":70,
}
print("Welcome to my res......")
print(menu)
order_total = 0

item_1 = input("Enter the name of item you want to order = ")

if item_1 in menu:
    order_total += menu[item_1]
    print(f"Your item {item_1} has been added to your order")
else:
    print(f"Ordered item {item_1} is not available yet!!")

another_order = input("Do you want to add another item? (Yes/No) ")

if another_order == "Yes":
    item_2 = input("Enter the name of second item = ")

    if item_2 in menu:
        order_total += menu[item_2]
        print(f"Item {item_2} has been added to order")
    else:
        print(f"Ordered {item_2} is not available")

print(f"The total amount of items to pay is {order_total}")

lab={
    "ramesh":60,
    "suresh":40,
    "ram":50,
    "shyam":90,
}
for keys in lab:
  print(f"Key: {keys}, Value: {lab[keys]}")

